### ISSUE TITLE
Add new sms queries / answers

### ISSUE THREAD

**Issue by bleucitron** [anthill/6brain#2]
# Queries
- "Logs": query ant logs
- "Ifconfig": query interface config
- "restart 6sense": in case 6sense is sleeping
- "Shell command": execute bash command on ant
# Messages when events occur
- "I'm up": when rebooted => should send the message to twilio
- "6sense sleeping"
- "6sense recording"
- "sms received from N°: msg content"
- "tunnel opened"
- "tunnel closed"

**to be continued**

**Comment by vallettea** [comment]
a way to change some parameter:
- set hour
- set measure frequency
