### ISSUE TITLE
6brain sends about 30 times more data since the move to MQTT and bluetooth

### ISSUE THREAD

**Issue by 4rzael** [anthill/6brain#24]
It's been noticed by @vallettea and @4rzael that we pay 30x more than we used to.
Before, we were sending 30KB/day. Recently, it's been noticed that sensors can send 500KB in a few hours.

We need to investigate on the causes.
- [x] Decide on a recording tool. We can either use WireShark or set up a TCP client in Node that will record all incoming messages and their sizes
- [x] Record what is actually being sent by sensors over a period of time including measurements and investigate the raw data to observe what is being sent.

MQTT spec. Might be useful to understand what's going on.

**Comment by 4rzael** [comment]
![wireshark](https://cloud.githubusercontent.com/assets/9220115/10458969/b0a4fdae-71cd-11e5-9c4c-6cb5ef09f6bd.png)

We receive and send some strange packets of 66-68 bytes every 10 seconds (~72KB per hour)

**Comment by DavidBruant** [comment]
Packets are sent by 3 every 10 secs, 2 of 68 bytes then 1 of 66 bytes. 66 bytes is the cost of Ethernet + IP + TCP headers. 
Source and destination alternate back and forth, so it looks like they're ping-pong'ing.

The 2 bytes of data are systematically `0xc000` and `0xd000` which looks **a lot** like MQTT's [PINGREQ](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718081) and [PINGRESP](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718086) payloads.
The third packet is a TCP ACK.

**Comment by 4rzael** [comment]
The problem was here:
https://github.com/4rzael/6brain/blob/edad2965def602f478865360d232571df42d4389/index.js#L100-L110

mqtt.connect only takes 2 arguments, so the third one was not taken in account.

Here's what it should look like:

```
client = mqtt.connect('mqtt://' + PRIVATE.connectInfo.host + ':' + PRIVATE.connectInfo.port,
                {
                    username: simId,
                    password: PRIVATE.connectInfo.password,
                    clientId: simId,
                    keepalive: 600, // Keep alive set to once every 10 minutes.
                    clean: false
                });
```

**Comment by DavidBruant** [comment]
In the end, we decide `keepalive` should be disabled entirely (set to 0)

**Comment by DavidBruant** [comment]
For reference, the WireShark screenshot above was taken under the following conditions:
- @4rzael's computer was running the pheromon server.
- Wireshark was running on @4rzael's computer (listening what was coming to pheromon).
- The sensor was connected to @4rzael's computer with an Ethernet cable and communicating via `192.168.x.x` addresses.
