### ISSUE TITLE
Choose an OS for deployment in 35 recylcing centers

### ISSUE THREAD

**Issue by DavidBruant** [anthill/6brain#26]

**Comment by DavidBruant** [comment]
Contenders : 
- ArchLinux
  => Cool, but touch screen is unlikely to work out of the box
- Rapsian Wheezy
  => Works, but no Docker
- Raspian Jessie
  => Not a lot of packages yet.
- Hypriot (modified Raspian Jessie with Docker)

**Comment by DavidBruant** [comment]
Current choice is Hypriot

**Comment by bleucitron** [comment]
http://blog.hypriot.com/post/a-touch-of-magic-controlling-kitematic-with-a-touch-display-on-the-raspberry-pi/

**Comment by vallettea** [comment]
current choice jessie
