### ISSUE TITLE
Reopen Tunnel after first connection

### ISSUE THREAD

**Issue by bleucitron** [anthill/6brain#3]
For now, when a first tunnel connection is opened and closed, the second tunnel connection will fail systematically, due to "Port already", on Kerrigan it seems.

**Comment by bleucitron** [comment]
I don't really remember, but this feels like outdated. Need confirmation @4rzael @vallettea ?

**Comment by 4rzael** [comment]
As I recall, this is not outdated, we still have this bug.

**Comment by vallettea** [comment]
this is when the the ssh tunnel is killed violently, works fine when closetunnnel is used.
