### ISSUE TITLE
Increase the MQTT reconnexion period

### ISSUE THREAD

**Issue by 4rzael** [anthill/6brain#31]
When a sensor is connected to the internet, but cannot connect to the MQTT server for some reason (DNS, server down, etc...), it tries to reconnect after a delay.

This delay is set in [mqtt.connect()](https://github.com/mqttjs/MQTT.js#connect) as reconnectPeriod and is 1 second by default (1000 millis).

This led to a big data consumption, so it has been changed to 29 seconds in #30.

Because of a bug (see in #30) in MQTT.js, it cannot be set to a higher value.

We should think about increasing again this value once the bug is fixed.

**Comment by vallettea** [comment]
this was corrected in mqtt by @4rzael
