### ISSUE TITLE
Problems with date.

### ISSUE THREAD

**Issue by 4rzael** [anthill/6brain#61]
At the moment, we have 6 old sensors installed, and since pheromon doesn't send the date anymore, none of them works. (Their record date is wrong, when they record)

Should we roll back to a version with the date until we change them, or do we keep this one ?

@vallettea

**Comment by SergeBredin** [comment]
In my opinion, we should roll-back temporarily because from 6element view, all sensors are down.
How do you feel with it @vallettea ?

**Comment by vallettea** [comment]
I don't think we should roll back. Can you make thé tunnel? If yes juste update them

**Comment by vallettea** [comment]
These sensors are zombies now, we should wait until we go there to change them. Anyway I stopped to pay their sims...
